flickr:
  epochs: 100
  batch_size: 6000
  subgraph_nodes: 17850

  hparams:
    hidden_units: 256
    dropout_rate:
    learning_rate:


reddit:
  epochs: 800
  batch_size: 3000
  subgraph_nodes: 8700

ppi:
  epochs: 3500
  batch_size: 3000
  subgraph_nodes: 9000

  hparams:
    hidden_units:
    dropout_rate:
    learning_rate:

ppi-large:
  epochs: 1500
  batch_size: 6000
  subgraph_nodes: 19000

  hparams:
    hidden_units:
    dropout_rate:
    learning_rate:

yelp:
  epochs: 300
  batch_size: 6000

  hparams:
    hidden_units:
    dropout_rate:
    learning_rate: